# Generated by Django 2.2.3 on 2019-07-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0002_auto_20190715_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(default='', max_length=50),
        ),
    ]
