# Generated by Django 2.2.3 on 2019-07-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
