# Generated by Django 2.2.3 on 2019-07-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0006_auto_20190715_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='movie_id',
            new_name='commented_movie',
        ),
    ]
